# Generated by Django 3.0.6 on 2020-05-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomment',
            old_name='question',
            new_name='answer',
        ),
    ]
