# Generated by Django 3.0.6 on 2020-05-28 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200528_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upvote', models.BooleanField(default=False)),
                ('Downvote', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upvote', models.BooleanField(default=False)),
                ('Downvote', models.BooleanField(default=False)),
                ('acceptanceStatus', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Answer')),
            ],
        ),
    ]
