# Generated by Django 3.0.6 on 2020-05-30 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0007_auto_20200530_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answercomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answerpoint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionpoint',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
